WITH callback_data AS (
  SELECT
    conv.identifier,
    conv.c_answered,
    conv.c_contact_connected_datetime,
    conv.c_call_answered_datetime,
    DATEDIFF(
      SECOND,
      conv.c_contact_connected_datetime,
      conv.c_call_answered_datetime
    ) AS time_to_callback_seconds
  FROM
    conv AS conv
  WHERE
    (
      conv.c_media_type = 'callback'
      OR (
        conv.c_direction_original = 'inbound'
        AND conv.c_direction = 'outbound'
      )
    )
)
SELECT
  MIN(c_contact_connected_datetime) AS start_date,
  MAX(c_contact_connected_datetime) AS end_date,
  COUNT(DISTINCT identifier) AS total_callbacks,
  COUNT(
    DISTINCT CASE
      WHEN c_answered = 1 THEN identifier
    END
  ) AS answered_callbacks,
  COUNT(
    DISTINCT CASE
      WHEN c_answered = 0 THEN identifier
    END
  ) AS unanswered_callbacks,
  COUNT(
    DISTINCT CASE
      WHEN c_answered = 1 THEN identifier
    END
  ) / NULLIF(NULLIF(COUNT(DISTINCT identifier), 0), 0) AS callback_success_rate,
  AVG(
    CASE
      WHEN c_answered = 1
      AND time_to_callback_seconds >= 0 THEN time_to_callback_seconds
    END
  ) AS avg_time_to_callback_seconds
FROM
  callback_data
  /* Generated by Cortex Analyst (request_id: 91578399-523f-40cb-986d-6887a948081c) */