WITH callback_data AS (
  SELECT
    conv.identifier,
    conv.c_answered,
    conv.c_contact_connected_datetime,
    conv.c_call_answered_datetime,
    DATEDIFF(
      SECOND,
      conv.c_contact_connected_datetime,
      conv.c_call_answered_datetime
    ) AS time_to_callback_seconds
  FROM
    conv AS conv
  WHERE
    conv.c_media_type = 'callback'
    OR (
      conv.c_direction_original = 'inbound'
      AND conv.c_direction = 'outbound'
    )
),
unique_callbacks AS (
  SELECT
    DISTINCT identifier,
    c_answered,
    c_contact_connected_datetime,
    c_call_answered_datetime,
    time_to_callback_seconds
  FROM
    callback_data
)
SELECT
  MIN(c_contact_connected_datetime) AS start_date,
  MAX(c_contact_connected_datetime) AS end_date,
  COUNT(identifier) AS total_callbacks,
  SUM(
    CASE
      WHEN c_answered = 1 THEN 1
      ELSE 0
    END
  ) AS answered_callbacks,
  SUM(
    CASE
      WHEN c_answered = 0 THEN 1
      ELSE 0
    END
  ) AS unanswered_callbacks,
  SUM(
    CASE
      WHEN c_answered = 1 THEN 1
      ELSE 0
    END
  ) / NULLIF(NULLIF(COUNT(identifier), 0), 0) AS callback_success_rate,
  AVG(
    CASE
      WHEN c_answered = 1
      AND time_to_callback_seconds >= 0 THEN time_to_callback_seconds
    END
  ) AS avg_time_to_callback_seconds
FROM
  unique_callbacks
  /* Generated by Cortex Analyst (request_id: d6b64855-fa06-4088-aabe-bdc8401160e8) */